{% set name = "xeus" %}
{% set version = "0.18.1" %}
{% set sha256 = "b2bf124d015399ba5a40bc77b80254c9217944223295a8b9b764ec179d0e4b9a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xeus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win and vc<14]
  {% if 'toolchain' in compiler('cxx') %}skip: True{% endif %}  # Only build with modern compilers.
  features:  # [win]
    - vc14  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - pkg-config  # [unix]
    - {{ compiler('cxx') }}
  host:
    - xtl >=0.5.0,<0.6
    - nlohmann_json >=3.2.0,<4.0
    - libuuid  # [linux]
    - cppzmq 4.3.0
    - zeromq 4.2.5
    - cryptopp 7.0.0
  # zeromq, cryptopp and libuuid have run_exports sections. No need to add them as run requirements.
  # xeus headers expose headers from nlohmann_json, cppzmq and xtl, but does not depend on them at runtime.
  run_constrained:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x') }}
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xeus  # [unix]
    - test -f ${PREFIX}/include/xeus/xeus.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus/xeusConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus/xeusConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_INC%\\xeus\\xeus.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus\\xeusConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus\\xeusConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xeus
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ implementation of the Jupyter Kernel protocol'
  description: 'xeus is a library meant to facilitate the implementation of kernels for Jupyter. It takes the burden of implementing the Jupyter Kernel protocol so developers can focus on implementing the interpreter part of the Kernel.'
  doc_url: http://xeus.readthedocs.io
  dev_url: https://github.com/QuantStack/xeus

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
